require 'httparty'

class WeatherDotGovAPI
  include HTTParty
  base_uri 'https://api.weather.gov'
  headers "User-Agent": "MyApplication/v1.2 (thanks for service; sample weather app)"

  def initialize(latitude, longitude)
    @grid = "#{latitude},#{longitude}"
  end

  def call
    points = get_points
    weather(points)
  rescue
    return { status: 500, error: "error with WeatherDotGovAPI" }
  end

  def get_points
    res = JSON.parse self.class.get("/points/" + @grid)
    # res.request.last_uri.to_s
    # ^^ showed we were hitting "https://api.weather.gov/points/?38.3146689,-85.60142"
    # which was incorrect, do not use query params
    return "#{res["properties"]["gridId"]}/#{res["properties"]["gridX"]},#{res["properties"]["gridY"]}"
  end
  def weather(points)
    res = JSON.parse self.class.get("/gridpoints/#{points}/forecast")
    weather = OpenStruct.new
    weather.details = res['properties']['periods'][0]['detailedForecast']
    weather.wind_speed = res['properties']['periods'][0]['windSpeed']
    weather.wind_direction = res['properties']['periods'][0]['windDirection']
    weather
  end
end

# example return
# {"@context"=>["https://geojson.org/geojson-ld/geojson-context.jsonld", {"@version"=>"1.1", "wx"=>"https://api.weather.gov/ontology#", "geo"=>"http://www.opengis.net/ont/geosparql#", "unit"=>"http://codes.wmo.int/common/unit/", "@vocab"=>"https://api.weather.gov/ontology#"}],
# "type"=>"Feature",
# "geometry"=>{"type"=>"Polygon", "coordinates"=>[[[-122.4263422, 37.7812437], [-122.42068499999999, 37.7594384], [-122.3931399, 37.7639016], [-122.39879169999999, 37.7857073], [-122.4263422, 37.7812437]]]},
# "properties"=>{"updated"=>"2023-03-16T23:01:31+00:00", "units"=>"us", "forecastGenerator"=>"BaselineForecastGenerator", "generatedAt"=>"2023-03-17T02:13:11+00:00", "updateTime"=>"2023-03-16T23:01:31+00:00", "validTimes"=>"2023-03-16T17:00:00+00:00/P7DT11H", "elevation"=>{"unitCode"=>"wmoUnit:m", "value"=>39.9288},
# "periods"=>[{"number"=>1, "name"=>"Tonight", "startTime"=>"2023-03-16T19:00:00-07:00", "endTime"=>"2023-03-17T06:00:00-07:00", "isDaytime"=>false, "temperature"=>44, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>7.222222222222222}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>92}, "windSpeed"=>"6 to 15 mph", "windDirection"=>"WSW", "icon"=>"https://api.weather.gov/icons/land/night/few?size=medium",
# "shortForecast"=>"Mostly Clear", "detailedForecast"=>"Mostly clear, with a low around 44. West southwest wind 6 to 15 mph, with gusts as high as 18 mph."},
#
# {"number"=>2, "name"=>"Friday", "startTime"=>"2023-03-17T06:00:00-07:00", "endTime"=>"2023-03-17T18:00:00-07:00", "isDaytime"=>true, "temperature"=>62, "temperatureUnit"=>"F", "temperatureTrend"=>"falling", "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>8.88888888888889}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>92}, "windSpeed"=>"5 to 18 mph", "windDirection"=>"W", "icon"=>"https://api.weather.gov/icons/land/day/sct?size=medium", "shortForecast"=>"Mostly Sunny", "detailedForecast"=>"Mostly sunny. High near 62, with temperatures falling to around 59 in the afternoon. West wind 5 to 18 mph, with gusts as high as 23 mph."},
# {"number"=>3, "name"=>"Friday Night", "startTime"=>"2023-03-17T18:00:00-07:00", "endTime"=>"2023-03-18T06:00:00-07:00", "isDaytime"=>false, "temperature"=>47, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>8.88888888888889}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>92}, "windSpeed"=>"7 to 17 mph", "windDirection"=>"W", "icon"=>"https://api.weather.gov/icons/land/night/bkn?size=medium", "shortForecast"=>"Mostly Cloudy", "detailedForecast"=>"Mostly cloudy, with a low around 47. West wind 7 to 17 mph, with gusts as high as 22 mph."},
# {"number"=>4, "name"=>"Saturday", "startTime"=>"2023-03-18T06:00:00-07:00", "endTime"=>"2023-03-18T18:00:00-07:00", "isDaytime"=>true, "temperature"=>63, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>20}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>10.555555555555555}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>94}, "windSpeed"=>"1 to 8 mph", "windDirection"=>"SW", "icon"=>"https://api.weather.gov/icons/land/day/bkn/rain_showers,20?size=medium", "shortForecast"=>"Partly Sunny then Slight Chance Rain Showers", "detailedForecast"=>"A slight chance of rain showers after 5pm. Partly sunny, with a high near 63. Southwest wind 1 to 8 mph. Chance of precipitation is 20%."},
# {"number"=>5, "name"=>"Saturday Night", "startTime"=>"2023-03-18T18:00:00-07:00", "endTime"=>"2023-03-19T06:00:00-07:00", "isDaytime"=>false, "temperature"=>50, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>60}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>8.88888888888889}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>91}, "windSpeed"=>"3 to 8 mph", "windDirection"=>"S", "icon"=>"https://api.weather.gov/icons/land/night/rain_showers,40/rain_showers,60?size=medium", "shortForecast"=>"Rain Showers Likely", "detailedForecast"=>"Rain showers likely. Cloudy, with a low around 50. South wind 3 to 8 mph. Chance of precipitation is 60%. New rainfall amounts between a tenth and quarter of an inch possible."},
# {"number"=>6, "name"=>"Sunday", "startTime"=>"2023-03-19T06:00:00-07:00", "endTime"=>"2023-03-19T18:00:00-07:00", "isDaytime"=>true, "temperature"=>58, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>60}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>11.11111111111111}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>94}, "windSpeed"=>"5 to 14 mph", "windDirection"=>"S", "icon"=>"https://api.weather.gov/icons/land/day/rain_showers,60/rain_showers,30?size=medium", "shortForecast"=>"Rain Showers Likely", "detailedForecast"=>"Rain showers likely. Mostly cloudy, with a high near 58. Chance of precipitation is 60%. New rainfall amounts between a tenth and quarter of an inch possible."},
# {"number"=>7, "name"=>"Sunday Night", "startTime"=>"2023-03-19T18:00:00-07:00", "endTime"=>"2023-03-20T06:00:00-07:00", "isDaytime"=>false, "temperature"=>50, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>50}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>10}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>91}, "windSpeed"=>"12 mph", "windDirection"=>"SW", "icon"=>"https://api.weather.gov/icons/land/night/rain_showers,30/rain_showers,50?size=medium", "shortForecast"=>"Chance Rain Showers", "detailedForecast"=>"A chance of rain showers. Mostly cloudy, with a low around 50. Chance of precipitation is 50%."},
# {"number"=>8, "name"=>"Monday", "startTime"=>"2023-03-20T06:00:00-07:00", "endTime"=>"2023-03-20T18:00:00-07:00", "isDaytime"=>true, "temperature"=>58, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>10}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>92}, "windSpeed"=>"12 to 21 mph", "windDirection"=>"SW", "icon"=>"https://api.weather.gov/icons/land/day/rain_showers?size=medium", "shortForecast"=>"Chance Rain Showers", "detailedForecast"=>"A chance of rain showers. Mostly cloudy, with a high near 58."},
# {"number"=>9, "name"=>"Monday Night", "startTime"=>"2023-03-20T18:00:00-07:00", "endTime"=>"2023-03-21T06:00:00-07:00", "isDaytime"=>false, "temperature"=>47, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>7.777777777777778}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>86}, "windSpeed"=>"12 to 21 mph", "windDirection"=>"SW", "icon"=>"https://api.weather.gov/icons/land/night/rain_showers?size=medium", "shortForecast"=>"Rain Showers", "detailedForecast"=>"Rain showers. Mostly cloudy, with a low around 47."},
# {"number"=>10, "name"=>"Tuesday", "startTime"=>"2023-03-21T06:00:00-07:00", "endTime"=>"2023-03-21T18:00:00-07:00", "isDaytime"=>true, "temperature"=>54, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>6.666666666666667}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>88}, "windSpeed"=>"12 to 18 mph", "windDirection"=>"WSW", "icon"=>"https://api.weather.gov/icons/land/day/rain_showers?size=medium", "shortForecast"=>"Rain Showers", "detailedForecast"=>"Rain showers. Mostly cloudy, with a high near 54."},
# {"number"=>11, "name"=>"Tuesday Night", "startTime"=>"2023-03-21T18:00:00-07:00", "endTime"=>"2023-03-22T06:00:00-07:00", "isDaytime"=>false, "temperature"=>45, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>5.555555555555555}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>81}, "windSpeed"=>"16 to 21 mph", "windDirection"=>"WNW", "icon"=>"https://api.weather.gov/icons/land/night/rain_showers?size=medium", "shortForecast"=>"Chance Rain Showers", "detailedForecast"=>"A chance of rain showers. Mostly cloudy, with a low around 45."},
# {"number"=>12, "name"=>"Wednesday", "startTime"=>"2023-03-22T06:00:00-07:00", "endTime"=>"2023-03-22T18:00:00-07:00", "isDaytime"=>true, "temperature"=>56, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>6.666666666666667}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>81}, "windSpeed"=>"14 to 21 mph", "windDirection"=>"WNW", "icon"=>"https://api.weather.gov/icons/land/day/rain_showers?size=medium", "shortForecast"=>"Chance Rain Showers", "detailedForecast"=>"A chance of rain showers. Partly sunny, with a high near 56."},
# {"number"=>13, "name"=>"Wednesday Night", "startTime"=>"2023-03-22T18:00:00-07:00", "endTime"=>"2023-03-23T06:00:00-07:00", "isDaytime"=>false, "temperature"=>44, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>5.555555555555555}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>80}, "windSpeed"=>"12 to 21 mph", "windDirection"=>"WNW", "icon"=>"https://api.weather.gov/icons/land/night/rain_showers/wind_sct?size=medium", "shortForecast"=>"Slight Chance Rain Showers then Partly Cloudy", "detailedForecast"=>"A slight chance of rain showers before 11pm. Partly cloudy, with a low around 44."},
# {"number"=>14, "name"=>"Thursday", "startTime"=>"2023-03-23T06:00:00-07:00", "endTime"=>"2023-03-23T18:00:00-07:00", "isDaytime"=>true, "temperature"=>57, "temperatureUnit"=>"F", "temperatureTrend"=>nil, "probabilityOfPrecipitation"=>{"unitCode"=>"wmoUnit:percent", "value"=>nil}, "dewpoint"=>{"unitCode"=>"wmoUnit:degC", "value"=>6.111111111111111}, "relativeHumidity"=>{"unitCode"=>"wmoUnit:percent", "value"=>82}, "windSpeed"=>"12 to 16 mph", "windDirection"=>"W", "icon"=>"https://api.weather.gov/icons/land/day/rain_showers?size=medium", "shortForecast"=>"Slight Chance Rain Showers", "detailedForecast"=>"A slight chance of rain showers between 11am and 5pm. Mostly sunny, with a high near 57."}]}}